name: blackwallet
description: A secure e-wallet application
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  flutter_stripe: ^12.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  local_auth: ^3.0.0
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.0.7
  path_provider: ^2.1.0
  pdf: ^3.11.0
  share_plus: ^10.0.3
  fl_chart: ^1.1.1
  permission_handler: ^12.0.1
  csv: ^6.0.0
  crypto: ^3.0.3
  url_launcher: ^6.3.0  # For SMS/email links
  email_validator: ^3.0.0  # Email validation
  provider: ^6.1.2  # Theme management
  flutter_contacts: ^1.1.7  # Contact picker
  nfc_manager: ^3.5.0  # NFC support
  flutter_email_sender: ^6.0.3  # Send emails
  flutter_sms: ^2.3.3  # Send SMS

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

